apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32001
  selector:
    app: web
  type: NodePort

